In [3]:
import pandas as pd

In [15]:
an = pd.read_csv('anagrafica_aziendale.csv', sep='\t')
ges = pd.read_csv('gestionale_paghe.csv')
si = pd.read_csv('sistema_hr.csv', sep=';')

In [23]:
si.head()

,Matricola,Cognome,Nome,Email,Reparto,Sede,DataAssunzione,Stipendio,DataNascita,Telefono,TipoContratto
0,EMP0001,Mancini,Viviana,viviana.mancini@azienda.it,Vendite,Bari,03/01/2010,"37974,75",24/03/1998,+39 055 2458591,Tempo Determinato
1,EMP0002,Pellegrini,Teresa,teresa.pellegrini@azienda.it,Vendite,Milano,27/11/2009,"38574,67",09/06/1975,+39 055 1445199,Tempo Indeterminato
2,EMP0003,Caruso,Irene,irene.caruso@azienda.it,Servizio Clienti,Perugia,11/12/2009,"27333,11",17/04/1965,+39 010 3678638,Collaborazione
3,EMP0004,Pellegrini,Sabrina,sabrina.pellegrini@azienda.it,Produzione,Bari,30/10/2009,"37533,32",02/04/1999,+39 011 2714803,Tempo Determinato
4,EMP0006,Bruno,Claudio,claudio.bruno@azienda.it,Legale,Catania,13/12/2017,"37968,30",17/08/1973,+39 081 2166941,Apprendistato

In [24]:
d_an =set(an['INDIRIZZO_EMAIL'].unique())
d_ges =set(ges['email'].unique())
d_si =set(si['Email'].unique())

In [30]:
dipendenti = d_an.union(d_ges).union(d_si)

In [36]:
len(dipendenti - d_an)

20

In [35]:
len(dipendenti - d_ges)

30

In [34]:
len(dipendenti - d_si)

40

In [37]:
total_dip = []

for email in dipendenti:
    temp_d = {email: {
        'anagrafica': 0,
        'gestionale': 0,
        'sistema_hr': 0
    }}
    if email in d_an:
        temp_d[email]['anagrafica'] = 1
    if email in d_ges:
        temp_d[email]['gestionale'] = 1
    if email in d_si:
        temp_d[email]['sistema_hr'] = 1

    total_dip.append(temp_d)

In [46]:
total_dip = []

for email in dipendenti:
    temp_d =[email]
    if email in d_an:
        temp_d.append(1)
    else:
        temp_d.append(0)


    if email in d_ges:
        temp_d.append(1)
    else:
        temp_d.append(0)

        
    if email in d_si:
        temp_d.append(1)
    else:
        temp_d.append(0)

    total_dip.append(temp_d)

In [49]:
df = pd.DataFrame(total_dip)

In [51]:
df.columns = ['email', 'anagrafica', 'gestionale', 'sistema_hr']

In [54]:
df

                                email  anagrafica  gestionale  sistema_hr
0              paolo.bruno@azienda.it           1           1           1
1             noemi.marini@azienda.it           1           1           1
2            edoardo.leone@azienda.it           1           1           1
3          giuseppe.vitale@azienda.it           1           1           1
4    alessandro.sorrentino@azienda.it           1           1           1
..                                ...         ...         ...         ...
985           chiara.ricci@azienda.it           1           1           1
986         elena.esposito@azienda.it           1           1           1
987            nadia.russo@azienda.it           1           1           1
988       valerio.damiani2@azienda.it           1           1           1
989      daniele.battaglia@azienda.it           1           1           1

[990 rows x 4 columns]

In [55]:
df['count'] = df['anagrafica'] + df['gestionale'] + df['sistema_hr']

In [63]:
solo_due = df[df['count'] == 2]

In [67]:
solo_due.groupby(['anagrafica', 'gestionale', 'sistema_hr']).size()

anagrafica  gestionale  sistema_hr
0           1           1              5
1           1           0             25
dtype: int64

In [68]:
solo_due

                             email  anagrafica  gestionale  sistema_hr  count
37      sergio.esposito@azienda.it           1           1           0      2
75     claudio.ruggiero@azienda.it           1           1           0      2
83          greta.serra@azienda.it           1           1           0      2
147         alice.ricci@azienda.it           1           1           0      2
169      roberto.marini@azienda.it           1           1           0      2
174       claudio.rossi@azienda.it           1           1           0      2
199       serena.caruso@azienda.it           1           1           0      2
255     davide.desantis@azienda.it           1           1           0      2
280       edoardo.rossi@azienda.it           1           1           0      2
281       debora.guerra@azienda.it           1           1           0      2
318     roberta.mariani@azienda.it           1           1           0      2
356         elia.donati@azienda.it           0           1           1      2
364        luca.ferraro@azienda.it           0           1           1      2
407   francesco.ferraro@azienda.it           1           1           0      2
443     elisa.graziano3@azienda.it           0           1           1      2
447       alberto.conti@azienda.it           1           1           0      2
469     barbara.carbone@azienda.it           1           1           0      2
504      beatrice.ferri@azienda.it           1           1           0      2
545    laura.sorrentino@azienda.it           1           1           0      2
643      chiara.rinaldi@azienda.it           0           1           1      2
655        elisa.derosa@azienda.it           1           1           0      2
699    umberto.ruggiero@azienda.it           1           1           0      2
727      giovanni.rossi@azienda.it           1           1           0      2
819        paolo.marino@azienda.it           0           1           1      2
822  raffaele.benedetti@azienda.it           1           1           0      2
838  adriano.sorrentino@azienda.it           1           1           0      2
849        elisa.grasso@azienda.it           1           1           0      2
879     salvatore.testa@azienda.it           1           1           0      2
934        davide.costa@azienda.it           1           1           0      2
962         elia.vitale@azienda.it           1           1           0      2